// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b0e2bafa-d6c9-43c1-8377-a7f348bb3fd0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_U6xO5O6TI",
    "aws_user_pools_web_client_id": "7mcqhhd2vev7m3dktknm1jrjb8",
    "oauth": {
        "domain": "clientappceb02595-ceb02595-localdev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000,https://master.dmish4eskhxxv.amplifyapp.com/,",
        "redirectSignOut": "http://localhost:3000,https://master.dmish4eskhxxv.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};

export default awsmobile;
